### PR TITLE
rename geo-compose -> geoview-compose

### PR DESCRIPTION
**Pull request by puneet-pdx**

### CODE REVIEW

**Review by shubham7109 — APPROVED** [review]
Happy to approve, all changes look good. Just two clarifications: 

- I think we would also update the logger warning to mention geoview-compose
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/f3660e9e02270b8b16095e1fda9ec06cd1915d02/toolkit/composable-map/build.gradle.kts#L19


- Would we also update the namespace for the module? Granted this change will impact all the current files to be moved to use a different package name. 
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/f3660e9e02270b8b16095e1fda9ec06cd1915d02/toolkit/geoview-compose/build.gradle.kts#L26

**Comment by markjdugger** [comment]
@puneet-pdx @shubham7109 
I agree with the 2nd bullet point in  [Shubham's comment above](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/361#pullrequestreview-1944779401).

In all the existing modules, we use the same name for the directory path in the Kotlin Toolkit repo _and_ the namespace. Almost all the other modules have a single word (authentication, compass, indoors, featureforms, and indoors) all follow that pattern. 

The only existing module that uses a hyphenated word is the deprecated composable-map. In that case the directory path uses `composable-map` and the namespace uses `composablemap` (since package names cannot have hyphens).

Thus, the analogous naming for `geoview-compose` module would be `geoview-compose` for the directory path and `geoviewcompose` for the namespace.

**Comment by puneet-pdx** [comment]
@hud10837 @shubham7109 @markjdugger I have made the changes to the namespace and the warning I missed earlier. Can you please review.

**Review by ruiqima — APPROVED** [review]
Looks good, approved. The only thing is the 2nd point in @shubham7109 comment is not fully addressed. In the `build.gradle.kts` file under the geoview-compose module, line 26, we need to also rename the `geocompose` there.

**Comment by markjdugger** [comment]
Looks good to me.

**Review by shubham7109 — APPROVED** [review]
Looks good, thanks @puneet-pdx

**Review by gunt0001 — APPROVED** [review]
@puneet-pdx - publishing looks good 👍

**Comment by puneet-pdx** [comment]
Thanks for the reviews everyone. Merging..

**Pull request merged**
