### PR TITLE
merge L10n staging to v.next

### PR DESCRIPTION
**Pull request by sorenoid**
refer to issue in Kotlin backlog https://devtopia.esri.com/runtime/kotlin/issues/3652

### CODE REVIEW

**Comment by sorenoid** [comment]
@michi6571 @masa6674 there are illegal unicode escape characters in several files and we cannot merge these translations as they are. For example in authentication/src/main/res/values-uk/strings.xml

`<string name="floor_filter_no_results">No s'ha trobat cap resultat.</string>` results in a build failure `Invalid unicode escape sequence in string`


```
2024-03-24T21:05:08.868-0700 [ERROR] [com.android.build.gradle.internal.res.ResourceCompilerRunnable$Companion] /Users/sor10874/git/github/arcgis-maps-sdk-kotlin-toolkit/toolkit/indoors/build/intermediates/packaged_res/debug/values-ca/values-ca.xml:3:4: Failed to flatten XML for resource 'floor_filter_no_results' with error: Invalid unicode escape sequence in string
"{str}"
```

**Comment by michi6571** [comment]
@sorenoid Thank you for the report.  We will review the issue. 

cc @MasaGithub88

**Comment by michi6571** [comment]
@sorenoid Thank you for your patience.  We fixed our Jenkins and create a new commit.  Could you please review the PR and let us know if you still see the issue?  
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/374

cc @MasaGithub88

**Comment by changanxian** [comment]
verified with the ZH local, It works as expected

**Review by changanxian — APPROVED** [review]

**Pull request merged**
