### PR TITLE
Format screenshots

### PR DESCRIPTION
**Pull request by shubham7109**
### Description

PR to format all the screenshots used in the readmes to allow for a max image height of `800px`

### CODE REVIEW

**Review by hud10837 — COMMENTED** [review]
Thanks for making this change. I notice that in some readmes we place the screenshot in a table, while in others we leave them inline. Could we normalize this with this PR? I think except for the Floor Filter microapp which uses a lot of screenshots, it makes sense to have them outside a table.

**Comment by shubham7109** [comment]
@hud10837 Good suggestion, I updated the screenshots to have them outside a table.

**Review by hud10837 — APPROVED** [review]
Thanks @shubham7109

**Review by changanxian — APPROVED** [review]
👍

**Pull request merged**
