### PR TITLE
Tabletop callout fix & Session config

### PR DESCRIPTION
**Pull request by gunt0001**
Related to issue: https://devtopia.esri.com/runtime/kotlin/issues/4769

### Description:

Fixes some issues and adds some refinements to TableTopSceneView.

Note - best to review this PR with `w=1`:
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/663/files?w=1

### Summary of changes:
- improves initialization and configuration of the ARCore Session, see changes in `ArSessionWrapper`:
   - `session` property is now a state flow of type `<Session?>`. Initially the session will be null and will only be created in `onResume`. This brings it inline with Google's [HelloAr sample](https://github.com/google-ar/arcore-android-sdk/blob/main/samples/hello_ar_kotlin/app/src/main/java/com/google/ar/core/examples/kotlin/common/helpers/ARCoreSessionLifecycleHelper.kt#L95-L104).
   - The session gets now configured in `onResume`.
   - During config we set `Config.LightEstimationMode.ENVIRONMENTAL_HDR`, which improves detection of planes on some devices.
   - In `TableTopSceneView` the session state flow is observed and only when a session is available, we create the `ArCameraFeed`
- Removed `onDrawStatusChanged` parameter from `TableTopSceneView`, since draw status changed events are never invoked when manual rendering is enabled (which is the case for TableTopSceneView).
- A change in the `SceneView()` composable function to invoke the content lambda when the scene view is ready OR when manual rendering is enabled. This is because when manual rendering is enabled (in the case of AR), we never receive a DrawStatusChanged event for `Completed`, thus the scene view would never be ready if we waited on it. So in cases where we render manually, we need to invoke the content lambda regardless of the draw status.
- Changes to `SceneViewProxy` to cache the `isManualRenderingEnabled` flag in a backing field and sync that with the SceneView when it is set on the proxy.

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [x] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/198/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

### CODE REVIEW

**Comment by puneet-pdx** [comment]
@gunt0001 LGTM 👍🏽

**Review by puneet-pdx — APPROVED** [review]
@gunt0001 LGTM 👍🏽

**Review by TADraeseke — APPROVED** [review]
LGTM!

**Comment by gunt0001** [comment]
Thanks @puneet-pdx @TADraeseke

**Pull request merged**
