### PR TITLE
Update feature branch with v.next

### PR DESCRIPTION
**Pull request by shubham7109**
### Description: 

PR to update the feature branch with the latest `v.next` dependency and release changes. 

The branch `shubham/feature-branch/geo-compose` is based of the current `feature-branches/geo-compose` and has the merge conflicts resolved from `v.next`.

- `feature-branches/geo-compose` compared to `v.next`: [Link](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/compare/feature-branches/geo-compose...v.next)

### CODE REVIEW

**Review by hud10837 — APPROVED** [review]
LGTM 👍

**Review by gunt0001 — APPROVED** [review]
@shubham7109 - looks good 👍

**Review by gunt0001 — CHANGES_REQUESTED** [review]
@shubham7109 - after cleaning my project locally I noticed the following compile error:
```
e: file:///Users/gunt0001/development/android/quartz-kotlin/arcgis-maps-sdk-kotlin-toolkit/microapps/mapviewidentifyapp/app/src/main/java/com/arcgismaps/toolkit/mapviewidentifyapp/screens/MainScreen.kt:56:9 Const 'val' has type 'Dp'. Only primitives and String are allowed
```

**Comment by shubham7109** [comment]
Nice catch, updated the branch with the recent changes from #228. The compile error should be resolved. Ready for review @gunt0001

**Review by gunt0001 — APPROVED** [review]
@shubham7109 - looks good 👍

**Review by gunt0001 — APPROVED** [review]
@shubham7109 - this works for me now 👍

**Pull request merged**
