### PR TITLE
200.4.0 post release version updates

### PR DESCRIPTION
**Pull request by puneet-pdx**
- Upgrade 3rd party dependencies
- bump version number for the sdk

### CODE REVIEW

**Review by eri9000 — COMMENTED** [review]
I see to be getting this error:
`sp-1.9.21-1.0.16 is too old for kotlin-1.9.23. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.21.`

**Comment by puneet-pdx** [comment]
@eri9000 I have upgraded the KSP version and created the issue for the Android Studio Iguana bug that is unrelated to the changes in this PR. 
https://devtopia.esri.com/runtime/kotlin/issues/3863

**Review by eri9000 — APPROVED** [review]
LGTM 👍🏼

**Review by ruiqima — APPROVED** [review]
LGTM 👍

**Comment by puneet-pdx** [comment]
Thanks @shubham7109 @ruiqima , merging..

**Pull request merged**
